/**
 * Lista os 66 livros da Bíblia (ordem canônica).
 * book_number 1–66 para uso na API de versículos.
 */
const BOOKS = [
  { number: 1, name: 'Gênesis', abbreviation: 'Gn' },
  { number: 2, name: 'Êxodo', abbreviation: 'Êx' },
  { number: 3, name: 'Levítico', abbreviation: 'Lv' },
  { number: 4, name: 'Números', abbreviation: 'Nm' },
  { number: 5, name: 'Deuteronômio', abbreviation: 'Dt' },
  { number: 6, name: 'Josué', abbreviation: 'Js' },
  { number: 7, name: 'Juízes', abbreviation: 'Jz' },
  { number: 8, name: 'Rute', abbreviation: 'Rt' },
  { number: 9, name: '1 Samuel', abbreviation: '1Sm' },
  { number: 10, name: '2 Samuel', abbreviation: '2Sm' },
  { number: 11, name: '1 Reis', abbreviation: '1Rs' },
  { number: 12, name: '2 Reis', abbreviation: '2Rs' },
  { number: 13, name: '1 Crônicas', abbreviation: '1Cr' },
  { number: 14, name: '2 Crônicas', abbreviation: '2Cr' },
  { number: 15, name: 'Esdras', abbreviation: 'Ed' },
  { number: 16, name: 'Neemias', abbreviation: 'Ne' },
  { number: 17, name: 'Ester', abbreviation: 'Et' },
  { number: 18, name: 'Jó', abbreviation: 'Jó' },
  { number: 19, name: 'Salmos', abbreviation: 'Sl' },
  { number: 20, name: 'Provérbios', abbreviation: 'Pv' },
  { number: 21, name: 'Eclesiastes', abbreviation: 'Ec' },
  { number: 22, name: 'Cânticos', abbreviation: 'Ct' },
  { number: 23, name: 'Isaías', abbreviation: 'Is' },
  { number: 24, name: 'Jeremias', abbreviation: 'Jr' },
  { number: 25, name: 'Lamentações', abbreviation: 'Lm' },
  { number: 26, name: 'Ezequiel', abbreviation: 'Ez' },
  { number: 27, name: 'Daniel', abbreviation: 'Dn' },
  { number: 28, name: 'Oseias', abbreviation: 'Os' },
  { number: 29, name: 'Joel', abbreviation: 'Jl' },
  { number: 30, name: 'Amós', abbreviation: 'Am' },
  { number: 31, name: 'Obadias', abbreviation: 'Ob' },
  { number: 32, name: 'Jonas', abbreviation: 'Jn' },
  { number: 33, name: 'Miqueias', abbreviation: 'Mq' },
  { number: 34, name: 'Naum', abbreviation: 'Na' },
  { number: 35, name: 'Habacuque', abbreviation: 'Hc' },
  { number: 36, name: 'Sofonias', abbreviation: 'Sf' },
  { number: 37, name: 'Ageu', abbreviation: 'Ag' },
  { number: 38, name: 'Zacarias', abbreviation: 'Zc' },
  { number: 39, name: 'Malaquias', abbreviation: 'Ml' },
  { number: 40, name: 'Mateus', abbreviation: 'Mt' },
  { number: 41, name: 'Marcos', abbreviation: 'Mc' },
  { number: 42, name: 'Lucas', abbreviation: 'Lc' },
  { number: 43, name: 'João', abbreviation: 'Jo' },
  { number: 44, name: 'Atos', abbreviation: 'At' },
  { number: 45, name: 'Romanos', abbreviation: 'Rm' },
  { number: 46, name: '1 Coríntios', abbreviation: '1Co' },
  { number: 47, name: '2 Coríntios', abbreviation: '2Co' },
  { number: 48, name: 'Gálatas', abbreviation: 'Gl' },
  { number: 49, name: 'Efésios', abbreviation: 'Ef' },
  { number: 50, name: 'Filipenses', abbreviation: 'Fp' },
  { number: 51, name: 'Colossenses', abbreviation: 'Cl' },
  { number: 52, name: '1 Tessalonicenses', abbreviation: '1Ts' },
  { number: 53, name: '2 Tessalonicenses', abbreviation: '2Ts' },
  { number: 54, name: '1 Timóteo', abbreviation: '1Tm' },
  { number: 55, name: '2 Timóteo', abbreviation: '2Tm' },
  { number: 56, name: 'Tito', abbreviation: 'Tt' },
  { number: 57, name: 'Filemon', abbreviation: 'Fm' },
  { number: 58, name: 'Hebreus', abbreviation: 'Hb' },
  { number: 59, name: 'Tiago', abbreviation: 'Tg' },
  { number: 60, name: '1 Pedro', abbreviation: '1Pe' },
  { number: 61, name: '2 Pedro', abbreviation: '2Pe' },
  { number: 62, name: '1 João', abbreviation: '1Jo' },
  { number: 63, name: '2 João', abbreviation: '2Jo' },
  { number: 64, name: '3 João', abbreviation: '3Jo' },
  { number: 65, name: 'Judas', abbreviation: 'Jd' },
  { number: 66, name: 'Apocalipse', abbreviation: 'Ap' },
];

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.status(200).json(BOOKS);
}
